[package]
name = "import-test-crate"
version = "0.1.0"
edition = "2021"

[dependencies]
try-partialord = { version = "0.1.3", registry = "test-local-registry" }
# try-partialord = { version = "0.1.3" }
# export-test-lib = { version = "0.1.0", registry = "test-local-registry" }
